# Generated by Django 4.2.9 on 2024-01-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachMatch',
            fields=[
                ('NoInTournament', models.IntegerField(blank=True, null=True)),
                ('LocalDate', models.DateField(blank=True, null=True)),
                ('LocalTime', models.TimeField(blank=True, null=True)),
                ('NoTeamA', models.CharField(blank=True, null=True)),
                ('NoTeamB', models.CharField(blank=True, null=True)),
                ('Court', models.CharField(blank=True, null=True)),
                ('MatchPointsA', models.CharField(blank=True, null=True)),
                ('MatchPointsB', models.CharField(blank=True, null=True)),
                ('PointsTeamASet1', models.CharField(blank=True, null=True)),
                ('PointsTeamBSet1', models.CharField(blank=True, null=True)),
                ('PointsTeamASet2', models.CharField(blank=True, null=True)),
                ('PointsTeamBSet2', models.CharField(blank=True, null=True)),
                ('PointsTeamASet3', models.CharField(blank=True, null=True)),
                ('PointsTeamBSet3', models.CharField(blank=True, null=True)),
                ('DurationSet1', models.CharField(blank=True, null=True)),
                ('DurationSet2', models.CharField(blank=True, null=True)),
                ('DurationSet3', models.CharField(blank=True, null=True)),
                ('No', models.CharField(primary_key=True, serialize=False)),
                ('Version', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeachRound',
            fields=[
                ('Code', models.CharField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, null=True)),
                ('Bracket', models.CharField(blank=True, null=True)),
                ('Phase', models.CharField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('No', models.IntegerField(primary_key=True, serialize=False)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeachTournament',
            fields=[
                ('Code', models.CharField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, null=True)),
                ('StartDateMainDraw', models.DateField(blank=True, null=True)),
                ('EndDateMainDraw', models.DateField(blank=True, null=True)),
                ('FederationCode', models.CharField(blank=True, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Code', models.CharField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FederationCode', models.CharField(blank=True, null=True)),
                ('FirstName', models.CharField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, null=True)),
                ('LastName', models.CharField(blank=True, null=True)),
                ('PlaysBeach', models.BooleanField()),
                ('PlaysVolley', models.BooleanField()),
                ('TeamName', models.CharField(blank=True, null=True)),
                ('No', models.IntegerField(blank=True, null=True)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeachTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoPlayer1', models.CharField(blank=True, null=True)),
                ('NoPlayer2', models.CharField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, null=True)),
                ('Rank', models.CharField(blank=True, null=True)),
                ('EarnedPointsTeam', models.CharField(blank=True, null=True)),
                ('EarningsTeam', models.CharField(blank=True, null=True)),
                ('No', models.IntegerField(unique=True)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('No', 'NoPlayer1', 'NoPlayer2')},
            },
        ),
    ]
